* collector class by location
* collector class by age
* collector class by SES
* collector class by billing_type
* collector class by character
* collector class by behavior
* collector class by demographics

# Install Library

In [ ]:
!pip install scikit-learn

In [ ]:
import pandas as pd
import numpy as np
import joblib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_curve, auc
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# Import Dataset

In [ ]:
data = pd.read_csv('Dummy Data Kolektor_Roviani Amelia_v04_20231008.csv')

# Modeling Kelas Kolektor

## By Location

###Pipeline Model

In [ ]:
df = pd.DataFrame(data)

# Pilih fitur-fitur yang ingin digunakan
selected_features = ['collector_location']

# Memisahkan data berdasarkan fitur yang dipilih
X = df[selected_features]
y = df['collector_island']

address_feature = 'collector_location'

address_transformer = Pipeline(steps=[
    ('tfidf', TfidfVectorizer()),
])

# Gabungkan transformers menggunakan ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('address', address_transformer, address_feature)
    ])

# Gabungkan preprocessor dengan model klasifikasi dalam pipeline
pipeline_collector_location = Pipeline(steps=[('preprocessor', preprocessor),
                           ('classifier', RandomForestClassifier())])

# Bagi data menjadi data pelatihan dan pengujian
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Latih pipeline pada data pelatihan
pipeline_collector_location.fit(X_train, y_train)

# Prediksi dengan pipeline
y_pred = pipeline_collector_location.predict(X_test)

# Evaluasi performa model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

# Tampilkan data nilai prediksi dan nilai seharusnya
results = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print("Data Nilai Prediksi dan Nilai Seharusnya:")
print(results)

# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Laporan Klasifikasi
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Accuracy: 1.0
Data Nilai Prediksi dan Nilai Seharusnya:
         Actual   Predicted
521    Sulawesi    Sulawesi
737        Jawa        Jawa
740  Kalimantan  Kalimantan
660  Kalimantan  Kalimantan
411       Papua       Papua
..          ...         ...
408    Sulawesi    Sulawesi
332        Bali        Bali
208    Sumatera    Sumatera
613       Papua       Papua
78        Papua       Papua

[200 rows x 2 columns]
Confusion Matrix:
[[19  0  0  0  0  0]
 [ 0 35  0  0  0  0]
 [ 0  0 26  0  0  0]
 [ 0  0  0 25  0  0]
 [ 0  0  0  0 36  0]
 [ 0  0  0  0  0 59]]
Classification Report:
              precision    recall  f1-score   support

        Bali       1.00      1.00      1.00        19
        Jawa       1.00      1.00      1.00        35
  Kalimantan       1.00      1.00      1.00        26
       Papua       1.00      1.00      1.00        25
    Sulawesi       1.00      1.00      1.00        36
    Sumatera       1.00      1.00      1.00        59

    accuracy                        

###Saving Model

In [ ]:
# Simpan model ke dalam file
joblib.dump(pipeline_collector_location, 'collector_class_by_location.joblib')
loaded_model_location = joblib.load('collector_class_by_location.joblib')

## By Age

###Pipeline Model

In [ ]:
df = pd.DataFrame(data)

# Memilih fitur-fitur yang ingin digunakan
selected_features = ['collector_age', 'collector_gender', 'collector_occupation',
                     'collector_education_level', 'collector_personality',
                     'year_experience', 'success_rate']

# Memisahkan data berdasarkan fitur yang dipilih
X = df[selected_features]
y = df['collector_age_class']

numeric_features = ['collector_age', 'year_experience', 'success_rate']

# Definisikan transformer untuk masing-masing tipe fitur
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

categorical_features = ['collector_gender', 'collector_occupation',
                        'collector_education_level', 'collector_personality']

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder())
])

# Gabungkan transformers menggunakan ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Gabungkan preprocessor dengan model klasifikasi dalam pipeline
pipeline_collector_age = Pipeline(steps=[('preprocessor', preprocessor),
                           ('classifier', RandomForestClassifier())])

# Bagi data menjadi data pelatihan dan pengujian
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Latih pipeline pada data pelatihan
pipeline_collector_age.fit(X_train, y_train)

# Prediksi dengan pipeline
y_pred = pipeline_collector_age.predict(X_test)

# Evaluasi performa model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

# Tampilkan data nilai prediksi dan nilai seharusnya
results = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print("Data Nilai Prediksi dan Nilai Seharusnya:")
print(results)

# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Laporan Klasifikasi
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Accuracy: 0.865
Data Nilai Prediksi dan Nilai Seharusnya:
     Actual Predicted
521    Muda      Muda
737    Muda      Muda
740  Dewasa    Dewasa
660    Muda       Tua
411    Muda      Muda
..      ...       ...
408    Muda      Muda
332     Tua       Tua
208  Dewasa    Dewasa
613     Tua       Tua
78     Muda      Muda

[200 rows x 2 columns]
Confusion Matrix:
[[60 12  0]
 [ 9 97  2]
 [ 0  4 16]]
Classification Report:
              precision    recall  f1-score   support

      Dewasa       0.87      0.83      0.85        72
        Muda       0.86      0.90      0.88       108
         Tua       0.89      0.80      0.84        20

    accuracy                           0.86       200
   macro avg       0.87      0.84      0.86       200
weighted avg       0.87      0.86      0.86       200



###Saving Model

In [ ]:
# Simpan model ke dalam file
joblib.dump(pipeline_collector_age, 'collector_class_by_age.joblib')
loaded_model_age = joblib.load('collector_class_by_age.joblib')

## By SES

###Pipeline Model

In [ ]:
df = pd.DataFrame(data)

# Pilih fitur-fitur yang ingin digunakan
selected_features = ['collector_monthly_income', 'collector_occupation',
                     'collector_marital_status', 'collector_education_level',
                     'collector_personality', 'experience_level', 'negotiation_skills']

# Memisahkan data berdasarkan fitur yang dipilih
X = df[selected_features]
y = df['collector_ses']

# Definisikan transformer untuk masing-masing tipe fitur
numeric_features = ['collector_monthly_income']

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

categorical_features = ['collector_occupation', 'collector_marital_status',
                        'collector_education_level', 'negotiation_skills',
                        'collector_personality', 'experience_level']

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder())
])

# Gabungkan transformers menggunakan ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Gabungkan preprocessor dengan model klasifikasi dalam pipeline
pipeline_collector_ses = Pipeline(steps=[('preprocessor', preprocessor),
                           ('classifier', RandomForestClassifier())])

# Bagi data menjadi data pelatihan dan pengujian
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Latih pipeline pada data pelatihan
pipeline_collector_ses.fit(X_train, y_train)

# Prediksi dengan pipeline
y_pred = pipeline_collector_ses .predict(X_test)

# Evaluasi performa model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

# Tampilkan data nilai prediksi dan nilai seharusnya
results = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print("Data Nilai Prediksi dan Nilai Seharusnya:")
print(results)

# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Laporan Klasifikasi
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Accuracy: 0.91
Data Nilai Prediksi dan Nilai Seharusnya:
    Actual Predicted
521      C         C
737      D         D
740      D         D
660      A         A
411      B         B
..     ...       ...
408      C         C
332      C         C
208      C         B
613      C         D
78       D         D

[200 rows x 2 columns]
Confusion Matrix:
[[42  3  0  0  0]
 [ 2 33  0  0  0]
 [ 0  2 27  5  0]
 [ 0  0  5 39  0]
 [ 0  0  0  1 41]]
Classification Report:
              precision    recall  f1-score   support

           A       0.95      0.93      0.94        45
           B       0.87      0.94      0.90        35
           C       0.84      0.79      0.82        34
           D       0.87      0.89      0.88        44
           E       1.00      0.98      0.99        42

    accuracy                           0.91       200
   macro avg       0.91      0.91      0.91       200
weighted avg       0.91      0.91      0.91       200



###Saving Model

In [ ]:
# Simpan model ke dalam file
joblib.dump(pipeline_collector_ses, 'collector_class_by_ses.joblib')
loaded_model_ses = joblib.load('collector_class_by_ses.joblib')

## By Field

###Pipeline Model

In [ ]:
df = pd.DataFrame(data)

# Pilih fitur-fitur yang ingin digunakan
selected_features = ['collector_gender', 'collector_age', 'collector_vehicle',
                     'negotiation_skills', 'proficient_technology_use',
                     'flexible_work', 'working_time', 'negotiation_result',
                     'year_experience', 'success_rate', 'handled_case_count',
                     'responsive_rate']

# Memisahkan data berdasarkan fitur yang dipilih
X = df[selected_features]
y = df['collector_workplace']

# Definisikan transformer untuk masing-masing tipe fitur
numeric_features = ['collector_age', 'year_experience', 'success_rate',
                    'handled_case_count', 'responsive_rate']

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

categorical_features = ['collector_gender', 'collector_vehicle',
                        'negotiation_skills', 'proficient_technology_use',
                        'flexible_work', 'working_time', 'negotiation_result']

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder())
])

# Gabungkan transformers menggunakan ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', categorical_transformer, categorical_features)
    ])

# Gabungkan preprocessor dengan model klasifikasi dalam pipeline
pipeline_collector_field = Pipeline(steps=[('preprocessor', preprocessor),
                           ('classifier', RandomForestClassifier())])

# Bagi data menjadi data pelatihan dan pengujian
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Latih pipeline pada data pelatihan
pipeline_collector_field.fit(X_train, y_train)

# Prediksi dengan pipeline
y_pred = pipeline_collector_field.predict(X_test)

# Evaluasi performa model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

# Tampilkan data nilai prediksi dan nilai seharusnya
results = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print("Data Nilai Prediksi dan Nilai Seharusnya:")
print(results)

# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Laporan Klasifikasi
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Accuracy: 1.0
Data Nilai Prediksi dan Nilai Seharusnya:
       Actual Predicted
521  Lapangan  Lapangan
737      Meja      Meja
740      Meja      Meja
660  Lapangan  Lapangan
411  Lapangan  Lapangan
..        ...       ...
408  Lapangan  Lapangan
332      Meja      Meja
208  Lapangan  Lapangan
613  Lapangan  Lapangan
78   Lapangan  Lapangan

[200 rows x 2 columns]
Confusion Matrix:
[[113   0]
 [  0  87]]
Classification Report:
              precision    recall  f1-score   support

    Lapangan       1.00      1.00      1.00       113
        Meja       1.00      1.00      1.00        87

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200



###Saving Model

In [ ]:
# Simpan model ke dalam file
joblib.dump(pipeline_collector_field, 'collector_class_by_collector_field.joblib')
loaded_model_field = joblib.load('collector_class_by_collector_field.joblib')

## By Behavior

###Pipeline Model

In [ ]:
df = pd.DataFrame(data)

# Pilih fitur-fitur yang ingin digunakan
selected_features = ['debtor_feedback', 'year_experience', 'experience_level',
                     'negotiation_result', 'success_rate', 'handled_case_category',
                     'handled_case_count', 'negotiation_skills', 'collector_personality',
                     'collector_occupation', 'collector_age']

# Memisahkan data berdasarkan fitur yang dipilih
X = df[selected_features]
y = df['debtor_behavior']

# Definisikan transformer untuk masing-masing tipe fitur
numeric_features = ['year_experience', 'success_rate', 'handled_case_count',
                    'collector_age']

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

categorical_features = ['debtor_feedback', 'experience_level', 'negotiation_result',
                        'handled_case_category', 'collector_occupation',
                        'collector_personality', 'negotiation_skills']

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder())
])

# Gabungkan transformers menggunakan ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Gabungkan preprocessor dengan model klasifikasi dalam pipeline
pipeline_behavior = Pipeline(steps=[('preprocessor', preprocessor),
                           ('classifier', RandomForestClassifier())])

# Bagi data menjadi data pelatihan dan pengujian
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Latih pipeline pada data pelatihan
pipeline_behavior.fit(X_train, y_train)

# Prediksi dengan pipeline
y_pred = pipeline_behavior.predict(X_test)

# Evaluasi performa model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

# Tampilkan data nilai prediksi dan nilai seharusnya
results = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print("Data Nilai Prediksi dan Nilai Seharusnya:")
print(results)

# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Laporan Klasifikasi
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Accuracy: 1.0
Data Nilai Prediksi dan Nilai Seharusnya:
          Actual    Predicted
521        Kabur        Kabur
737        Kabur        Kabur
740  Gagal Bayar  Gagal Bayar
660        Kabur        Kabur
411        Kabur        Kabur
..           ...          ...
408        Kabur        Kabur
332        Kabur        Kabur
208     Disiplin     Disiplin
613     Disiplin     Disiplin
78         Kabur        Kabur

[200 rows x 2 columns]
Confusion Matrix:
[[ 39   0   0]
 [  0  17   0]
 [  0   0 144]]
Classification Report:
              precision    recall  f1-score   support

    Disiplin       1.00      1.00      1.00        39
 Gagal Bayar       1.00      1.00      1.00        17
       Kabur       1.00      1.00      1.00       144

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200



###Saving Model

In [ ]:
# Simpan model ke dalam file
joblib.dump(pipeline_behavior, 'collector_class_by_debtor_behavior.joblib')
loaded_mode_behavior = joblib.load('collector_class_by_debtor_behavior.joblib')

## By Character

###Pipeline Model

In [ ]:
df = pd.DataFrame(data)

# Pilih fitur-fitur yang ingin digunakan
selected_features = ['communication_channel', 'collector_age', 'collector_gender',
                     'collector_education_level', 'negotiation_skills', 'collector_personality',
                     'year_experience', 'handled_case_count']

# Memisahkan data berdasarkan fitur yang dipilih
X = df[selected_features]
y = df['collector_style']

# Definisikan transformer untuk masing-masing tipe fitur
numeric_features = ['collector_age', 'year_experience', 'handled_case_count']

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

categorical_features = ['communication_channel', 'collector_gender',
                        'collector_education_level', 'negotiation_skills',
                        'collector_personality']

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder())
])

# Gabungkan transformers menggunakan ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Gabungkan preprocessor dengan model klasifikasi dalam pipeline
pipeline_character = Pipeline(steps=[('preprocessor', preprocessor),
                           ('classifier', RandomForestClassifier())])

# Bagi data menjadi data pelatihan dan pengujian
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Latih pipeline pada data pelatihan
pipeline_character.fit(X_train, y_train)

# Prediksi dengan pipeline
y_pred = pipeline_character.predict(X_test)

# Evaluasi performa model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

# Tampilkan data nilai prediksi dan nilai seharusnya
results = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print("Data Nilai Prediksi dan Nilai Seharusnya:")
print(results)

# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Laporan Klasifikasi
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Accuracy: 1.0
Data Nilai Prediksi dan Nilai Seharusnya:
        Actual  Predicted
521  Bijaksana  Bijaksana
737      Kasar      Kasar
740      Tegas      Tegas
660  Bijaksana  Bijaksana
411  Bijaksana  Bijaksana
..         ...        ...
408      Kasar      Kasar
332      Kasar      Kasar
208      Ramah      Ramah
613  Bijaksana  Bijaksana
78       Tegas      Tegas

[200 rows x 2 columns]
Confusion Matrix:
[[39  0  0  0]
 [ 0 43  0  0]
 [ 0  0 30  0]
 [ 0  0  0 88]]
Classification Report:
              precision    recall  f1-score   support

   Bijaksana       1.00      1.00      1.00        39
       Kasar       1.00      1.00      1.00        43
       Ramah       1.00      1.00      1.00        30
       Tegas       1.00      1.00      1.00        88

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200



###Saving Model

In [ ]:
# Simpan model ke dalam file
joblib.dump(pipeline_character, 'collector_class_by_debtor_character.joblib')
loaded_model_character = joblib.load('collector_class_by_debtor_character.joblib')

## By Demography

###Pipeline Model

In [ ]:
df = pd.DataFrame(data)

# Pilih fitur-fitur yang ingin digunakan
selected_features = ['collector_occupation', 'collector_monthly_income',
                     'collector_marital_status', 'collector_age',
                     'handled_case_category', 'collector_education_level',
                     'collector_vehicle', 'negotiation_skills', 'collector_personality',
                     'experience_level', 'success_rate']

# Memisahkan data berdasarkan fitur yang dipilih
X = df[selected_features]
y = df['demography_class']

# Definisikan transformer untuk masing-masing tipe fitur
numeric_features = ['collector_monthly_income', 'collector_age', 'success_rate']

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

categorical_features = ['collector_occupation', 'collector_marital_status',
                        'handled_case_category', 'collector_education_level',
                        'collector_vehicle', 'negotiation_skills',
                        'collector_personality', 'experience_level']

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder())
])

# Gabungkan transformers menggunakan ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Gabungkan preprocessor dengan model klasifikasi dalam pipeline
pipeline_demography = Pipeline(steps=[('preprocessor', preprocessor),
                           ('classifier', RandomForestClassifier())])

# Bagi data menjadi data pelatihan dan pengujian
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Latih pipeline pada data pelatihan
pipeline_demography.fit(X_train, y_train)

# Prediksi dengan pipeline
y_pred = pipeline_demography.predict(X_test)

# Evaluasi performa model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

# Tampilkan data nilai prediksi dan nilai seharusnya
results = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print("Data Nilai Prediksi dan Nilai Seharusnya:")
print(results)

# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Laporan Klasifikasi
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Accuracy: 0.98
Data Nilai Prediksi dan Nilai Seharusnya:
                       Actual                 Predicted
521  Pemukiman Padat Penduduk  Pemukiman Padat Penduduk
737  Pemukiman Padat Penduduk  Pemukiman Padat Penduduk
740                     Rusun                     Rusun
660  Pemukiman Padat Penduduk  Pemukiman Padat Penduduk
411                 Perumahan                 Perumahan
..                        ...                       ...
408  Pemukiman Padat Penduduk  Pemukiman Padat Penduduk
332  Pemukiman Padat Penduduk  Pemukiman Padat Penduduk
208  Pemukiman Padat Penduduk  Pemukiman Padat Penduduk
613  Pemukiman Padat Penduduk  Pemukiman Padat Penduduk
78   Pemukiman Padat Penduduk  Pemukiman Padat Penduduk

[200 rows x 2 columns]
Confusion Matrix:
[[ 0  0  4  0]
 [ 0 96  0  0]
 [ 0  0 58  0]
 [ 0  0  0 42]]
Classification Report:
                          precision    recall  f1-score   support

               Apartemen       0.00      0.00      0.00         4
Pemukiman Pa

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


###Saving Model

In [ ]:
# Simpan model ke dalam file
joblib.dump(pipeline_demography, 'collector_class_by_debtor_demography.joblib')
loaded_model_demography = joblib.load('collector_class_by_debtor_demography.joblib')